default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  primary:
    <<: *default
    database: navody_slovensko_digital_development
  datahub:
    <<: *default
    url: <%= ENV['DATAHUB_DATABASE_URL'] %>
    replica: true

test:
  primary:
    <<: *default
    database: navody_slovensko_digital_test
  datahub:
    <<: *default
    database: datahub_test
    replica: true

staging:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  datahub:
    <<: *default
    url: <%= ENV['DATAHUB_DATABASE_URL'] %>
    replica: true

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  datahub:
    <<: *default
    url: <%= ENV['DATAHUB_DATABASE_URL'] %>
    replica: true